#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides VpcId="vpc-095119748509b8bc4 " WebServerSGGroupId="sg-09efa4b03e58f1845" Subnets="subnet-0e0fd31733061237d,subnet-0377c6b172e2951d4,subnet-0d8058cb02f147a86" \
--region  \
--stack-name $STACK_NAME
